@Dimensions.Api_HostAddress = http://localhost:5249

### Public API
GET {{Dimensions.Api_HostAddress}}/api/public/system-info
Accept: application/json

### User Protected Business API
POST {{Dimensions.Api_HostAddress}}/api/customer/query
Content-Type: application/json
Authorization: Bearer {{user_token}}

{
  "customerId": "CUST-001",
  "keyword": "Kevin"
}
